export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_INVENTORY = 'GET_INVENTORY';
export const INVENTORY_ERROR = 'INVENTORY_ERROR';
export const UPDATE_INVENTORY = 'UPDATE INVENTORY';
